#!/bin/bash
thisdir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
JARFILE=ixa-pipe-ned-1.1.6.jar
cd $thisdir
# Need to set:
# 1. URL of Spotlight host
# 2. Port for Spotlight
# 3. Location of wikipedia-db
opts=""
while getopts h:p:w opt; do
   case $opt in
     h) SPOTHOST=$OPTARG
        ;;
     p) SPOTPORT=$OPTARG
        ;;
     w) WIKIDB=$OPTARG
        ;;
     *) echo "Unknown option." 
        exit 1
        ;;
    esac
done


SPOTHOST_DEF=localhost
SPOTHOST=${SPOTHOST:-${SPOTHOST_DEF}}

case ${naflang} in
   de) SPOTPORT_DEF=2010
       ;;
   en) SPOTPORT_DEF=2020
       ;;
   es) SPOTPORT_DEF=2030
       ;;
   fr) SPOTPORT_DEF=2040
       ;;
   it) SPOTPORT_DEF=2050
       ;;
   nl) SPOTPORT_DEF=2060
       ;;
   *) SPOTPORT_DEF=2020
       ;;
esac
SPOTPORT=${SPOTPORT:-${SPOTPORT_DEF}}

WIKIDB_DEF=${thisdir}/lib/wikipedia-db
WIKIDB=${WIKIDB:-${WIKIDB_DEF}}
if
  [ "${WIKIDB}x" == "x" ] || [ "${naflang}" == "en" ]
then
  wikip_arg=""
else 
  wikip_arg="-i ${WIKIDB} -n ${naflang}En"
fi

# cat | java -Xmx1000m -jar $JARFILE -H ${SPOTHOST} -p ${SPOTPORT} -e candidates ${wikip_arg} 
echo  java -Xmx1000m -jar $JARFILE -H ${SPOTHOST} -p ${SPOTPORT} -e candidates ${wikip_arg} 
